#!/usr/bin/env bash
# This script is used by a Continuous Integration job to auto-generate
# some components of the OMERO documentation from its deliverables (server,
# clients). To run it locally:
# - download the server and rename the folder as OMERO.server.
# - Clone the ome/omero-install repository as omero-install.

set -u
set -e
set -x
set -o pipefail
WORKSPACE=${WORKSPACE:-$(pwd)}
USER=${USER:-$(whoami)}

echo "Copying history"
# inject link to change log
touch newfile.rst
cat omero/changelog.rst > newfile.rst
cat $WORKSPACE/OMERO.server/history.rst >> newfile.rst
mv newfile.rst omero/users/history.rst

echo "Generating configuration properties page"
omero config parse --rst | sed "s|$WORKSPACE|/home/omero|" > omero/sysadmins/config.rst

echo "Generating ldap setdn usage page"
mkdir -p omero/downloads/ldap
(cd $WORKSPACE/OMERO.server && omero ldap setdn -h) > omero/downloads/ldap/setdn.out

echo "Generating advanced CLI help"
(cd $WORKSPACE/OMERO.server && omero import --advanced-help) 2> advanced-help.txt || echo "Dumped"
sed 1,5d advanced-help.txt > omero/downloads/inplace/advanced-help.txt
(cd $WORKSPACE/OMERO.server && omero import --javahelp) 2> java-help.txt || echo "Dumped"
sed 1,5d java-help.txt > omero/downloads/cli/help.out

echo "Generating DB script example"
(cd $WORKSPACE && omero db script --password secretpassword 2>&1) | sed "s|$WORKSPACE|/home/omero|" > omero/downloads/cli/db-script-example.txt

echo "Generating Web configuration templates"
# Nginx / WSGI
omero config set omero.web.application_server wsgi-tcp
omero web config nginx | sed "s|$WORKSPACE/OMERO.server|/home/omero/OMERO.py|g" > omero/sysadmins/unix/install-web/nginx-omero.conf
omero web config nginx-location | sed "s|$WORKSPACE/OMERO.server|/home/omero/OMERO.py|g" | grep -v '^#' > omero/sysadmins/unix/install-web/nginx-location.conf
omero web config nginx-location | sed "s|/opt/omero/web|/home/omero|g" | grep '^##' | cut -c3-
> omero/sysadmins/unix/install-web/nginx-location-manual-wrapper.conf

echo "Generating omeroweb install walkthrough"

(cd $WORKSPACE/omeroweb-install && ansible-playbook ./.travis/../ansible/omeroweb-install-doc.yml -i ./.travis/../ansible/hosts/centos7-ice3.6 --extra-vars '{"os": "centos7", "ice_version": "3.6", "clean": True}')
(cd $WORKSPACE/omeroweb-install && ansible-playbook ./.travis/../ansible/omeroweb-install-doc.yml -i ./.travis/../ansible/hosts/ubuntu-ice3.6 --extra-vars '{"os": "ubuntu", "ice_version": "3.6", "clean": True}')
(cd $WORKSPACE/omeroweb-install && ansible-playbook ./.travis/../ansible/omeroweb-install-doc.yml -i ./.travis/../ansible/hosts/osx-ice3.6 --extra-vars '{"os": "osx", "ice_version": "3.6", "clean": True}')
(cd $WORKSPACE/omeroweb-install && ansible-playbook ./.travis/../ansible/omeroweb-install-doc.yml -i ./.travis/../ansible/hosts/debian-ice3.6 --extra-vars '{"os": "debian", "ice_version": "3.6", "clean": True}')

mv $WORKSPACE/omeroweb-install/ansible/doc/* $WORKSPACE/ome-documentation/omero/sysadmins/unix/install-web/walkthrough

echo "Copying omero-install Linux scripts"
DIRECTORY=omero/sysadmins/unix/walkthrough/
if [ -d "$DIRECTORY" ]; then
	rm -rf $DIRECTORY
fi

mkdir -p $DIRECTORY/osx/
#generate walkthrough for all os
ALL=true bash $WORKSPACE/omero-install/linux/autogenerate.sh
cp walkthrough_*.sh $DIRECTORY
rm walkthrough_*.sh

for f in \
    README.md \
    requirements\* \
    settings.env \
    settings-web.env \
    setup_\* \
    omero-\* \
    ; do
    cp $WORKSPACE/omero-install/linux/$f $DIRECTORY
done

for f in \
    step* \
    install_* \
    ; do
    cp $WORKSPACE/omero-install/osx/$f $DIRECTORY/osx/
done

echo "Getting db properties"
omero/autogen_db_version.py $WORKSPACE/OMERO.server > omero/conf_autogen.py

echo "Cleanup"
rm java-help.txt
rm advanced-help.txt
