#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# ome documentation build configuration file, created by
# sphinx-quickstart on Wed Feb 22 20:24:38 2012.
#
# This file is execfile()d with the current directory set to its containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

import sys, os

# Append the top level directory of the docs, so we can import from the config dir.
sys.path.insert(0, os.path.abspath('../common'))
from conf import *


# -- General configuration -----------------------------------------------------

# General information about the project.
project = u'OME Model and Formats'
title = project + u' Documentation'

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
release = '2015-01'
version = '2015-01'

# OME model-specific extlinks
model_extlinks = {
    # Github links
    'source' : (bf_github_root + 'blob/'+ branch + '/%s', ''),
    'sourcedir' : (bf_github_root + 'tree/'+ branch + '/%s', ''),
    'omero_source' : (omero_github_root + 'blob/'+ branch + '/%s', ''),
    # API
    'javadoc' : (downloads_root + '/latest/bio-formats/api/%s', ''),
    # Doc links
    'omero_doc' : (oo_site_root + '/support/omero/%s', ''),
    'bf_doc' : (oo_site_root + '/support/bio-formats/%s', ''),
    'schema_doc' : (oo_root + '/Schemas/Documentation/Generated/OME-' + release + '/%s', ''),
    # Downloads
    'bf_downloads' : (downloads_root + '/latest/bio-formats/%s', ''),
    'image_downloads' : (downloads_root + '/images/%s', ''),
    'ometiff_downloads' : (downloads_root + '/images/OME-TIFF/' + release + '/%s', ''),
    'omexml_downloads' : (downloads_root + '/images/OME-XML/' + release + '/%s', ''),
    }
extlinks.update(model_extlinks)


# Edit on GitHub prefix
edit_on_github_prefix = 'formats'

# -- Options for LaTeX output --------------------------------------------------

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title, author, documentclass [howto/manual]).
target = 'OME-Model-' + release + '.tex'
latex_documents = [
  (master_doc, target, title, author, 'manual'),
]

# The name of an image file (relative to this directory) to place at the top of
# the title page.
latex_logo = '../common/images/ome-tight.pdf'
